import Header from "@/components/header";
import Footer from "@/components/footer";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Product | eCommerce",
  description: "Generated by create next app",
};

export default function Principal({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header>
        <Header />
      </header>
      <main>{children}</main>
      
      <footer>
        <Footer />
      </footer>
    </>
  );
}